### ISSUE TITLE
protobuf 3.19.3 error ModuleNotFoundError: No module named 'generated_python'

### ISSUE THREAD

**Issue by KyferEz** [scito/extract_otp_secret_keys#8]
c:\Programs\Python38-32>pip3 install protobuf
Requirement already satisfied: protobuf in c:\programs\python38-32\lib\site-packages (3.19.3)

c:\Programs\Python38-32>python extract_otp_secret_keys.py c:\programs\new.txt
Traceback (most recent call last):
  File "..\extract_otp_secret_keys.py", line 51, in <module>
    import generated_python.google_auth_pb2
ModuleNotFoundError: No module named 'generated_python'

c:\Programs\Python38-32>python
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import generated_python.google_auth_pb2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'generated_python'
>>> ^Z

**Comment by KyferEz** [comment]
Nevermind. Fixed by downloading the full source package. I missed a necessary folder when trying to manually download individual files.
